# Install uchiwa
---

- name: Copy rpm file to server
  copy:
     src: ../files/uchiwa-1.1.2-1.el7.x86_64.rpm
     dest: /tmp/uchiwa-1.1.2-1.el7.x86_64.rpm
  when: ansible_os_family == 'RedHat'

- name: Install uchiwa package.
  yum:
     name: /tmp/uchiwa-1.1.2-1.el7.x86_64.rpm
     state: present
  when: ansible_os_family == 'RedHat'
  
