---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==1.9.2

  # Create an inventory file for testing.
  - "echo 'uchiwa-standalone ansible_ssh_host=localhost' > inventory"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i inventory vagrant/site.yml --syntax-check"

  # Run the playbook
  - "ansible-playbook -vvvv -i inventory vagrant/site.yml --connection=local --sudo"
