    
# Install rabbitmq and erlang
---

- name: Copy erlang rpm file to server
  copy:
     src: "{{ erlang_version }}"
     dest: "/tmp/{{ erlang_version }}"
  when: erlang_install
  tags: install

- name: Copy rabbitmq rpm file to server
  copy:
     src: "{{ rabbitmq_version }}"
     dest: "/tmp/{{ rabbitmq_version }}"
  when: rabbitmq_install
  tags: install 

- name: Install erlang package.
  yum:
     name: "/tmp/{{ erlang_version }}"
     state: present
  when: erlang_install
  tags: install
  
- name: Install rabbitmq package.
  yum:
     name: "/tmp/{{ rabbitmq_version }}"
     state: present
  when: rabbitmq_install
  tags: install
  

  
