---

- name: Lookup OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
 
- name: Install apache packages for RedHat
  yum: "name={{ item }} state=present"
  with_items: "{{ apache_pkgs }}"
  when: ansible_os_family == 'RedHat'


