---
# tasks/client.yml: Deploy various client-side configurations for Sensu

  - name: copy the init.d sensu startup script
    template:
      dest: "/etc/init.d/sensu.service"
      src: "{{ sensu_startup_config }}"
      mode: "+x"
    tags: 
       - sensu-client    
  
  - name: Deploy Sensu client service configuration
    template:
      dest: "{{ sensu_config_path }}/conf.d/client.json"
      owner: "{{ sensu_user_name }}"
      group: "{{ sensu_group_name }}"
      src: "{{ sensu_client_config  }}"
      mode: "0640"
    notify: restart sensu-client service
    tags: sensu-client

  - name: Ensure Sensu client service is running
    service:
      name: "{{ sensu_client_service_name }}"
      state: started
      enabled: yes
    tags: sensu-client