---
# tasks/client.yml: Deploy various client-side configurations for Sensu

  - name: copy the init.d sensu startup script
    template:
      dest: "/etc/init.d/sensu.service"
      src: "{{ sensu_startup_config }}"
      mode: "+x"
    tags: 
       - sensu-server
    
  - name: Deploy Sensu server service configuration
    template:
      dest: "{{ sensu_config_path }}/conf.d/api.json"      
      src: "{{ sensu_server_config  }}"          
    tags: sensu-server
    
  - name: Deploy Sensu server redis configuration
    template:
      dest: "{{ sensu_config_path }}/conf.d/redis.json"      
      src: "{{ sensu_server_redis_config  }}"         
    tags: sensu-server
    
  - name: Deploy Sensu server rabbitmq configuration
    template:
      dest: "{{ sensu_config_path }}/conf.d/rabbitmq.json"      
      src: "{{ sensu_server_rabbitmq_config  }}"      
    tags: sensu-server
    
  - name: Ensure Sensu server service is running
    service:
      name: "{{ sensu_server_service_name }}"
      state: started
      enabled: yes
    tags: sensu-server