---

# get_url on Ansible 1.x only supports sha256 checksumming, so we're only
# using `redis_checksums` on Ansible 2.x because they're sha1.
- name: set redis checksum
  set_fact:
    redis_checksum: "{{ 'sha1' if redis_checksums[redis_version]|length == 40 else 'sha256' }}:{{ redis_checksums[redis_version] }}"
  when:
    - redis_verify_checksum|bool
    - redis_checksum is not defined
    - redis_version in redis_checksums
    - ansible_version.major >= 2

- name: create redis src directory
  file:
    path: "/data/redis/src"
    state: directory

#- name: download redis (ansible 1.x)
#  get_url:
#    url: "{{ redis_download_url }}"
#    dest: /data/redis/src/redis-{{ redis_version }}.tar.gz
#    sha256sum: "{{ redis_checksum|default(omit) }}"
#  when:
#    - not redis_tarball
#    - ansible_version.major < 2

#- name: download redis (ansible 2.x)
#  get_url:
#    url: "{{ redis_download_url }}"
#    dest: /data/redis/src/redis-{{ redis_version }}.tar.gz
#    checksum: "{{ redis_checksum|default(omit) }}"
#  when:
#    - not redis_tarball
#    - ansible_version.major >= 2
    
- name: download and copy redis file to server
  copy:
     src: "../files/{{ redis_version_file }}"
     dest: "/data/redis/src/{{ redis_version_file }}"
  when: redis_install
  tags: install

- name: upload redis
  copy:
    src: "{{ redis_tarball }}"
    dest: /data/redis/src/redis-{{ redis_version }}.tar.gz
  when: redis_tarball|default(false)

- name: extract redis tarball
  unarchive:
    src: /data/redis/src/redis-4.0.8.tar.gz
    dest: /data/redis/src
    creates: /data/redis/src/redis-{{ redis_version }}/Makefile
    copy: no
