---
- name: enable overcommit in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  when: redis_travis_ci is not defined

- name: compile redis
  command: make -j{{ ansible_processor_cores|default(1) + 1 }}{{ ' 32bit' if redis_make_32bit|bool else '' }}
  args:
    chdir: /data/redis/src/redis-{{ redis_version }}
    creates: /dta/redis/src/redis-{{ redis_version }}/src/redis-server

- name: create redis install directory
  file:
    path: "{{ redis_install_dir }}"
    state: directory

- name: create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /data/redis
    - /data/redis/etc
    - /data/redis/etc/redis
    - /data/redis/etc/tmpfiles.d

- name: check if redis user exists (ignore errors)
  command: id {{ redis_user }}
  ignore_errors: yes
  changed_when: false
  register: user_exists

- name: add redis group
  group:
    name: "{{ redis_group }}"
    state: present
  when: user_exists|failed

- name: add redis user
  user:
    name: "{{ redis_user }}"
    group: "{{ redis_group }}"
    comment: "Redis"
    home: "{{ redis_install_dir }}"
    shell: /bin/false
    system: yes
  when: user_exists|failed

- name: create /data/redis/run
  file:
    path: /data/redis/run
    state: directory
    owner: "{{ redis_user }}"

- name: install redis
  command: make PREFIX={{ redis_install_dir }} install
  args:
    chdir: /data/redis/src/redis-{{ redis_version }}
    creates: "{{ redis_install_dir }}/bin/redis-server"

- name: list redis binaries to add to alternatives
  command: ls -1 {{ redis_install_dir }}/bin
  register: redis_binaries
  changed_when: false

- name: add redis binaries to alternatives
  alternatives:
    name: "{{ item }}"
    path: "{{ redis_install_dir }}/bin/{{ item }}"
    link: "/usr/bin/{{ item }}"
  with_items: "{{ redis_binaries.stdout_lines }}"
