---
- hosts: dqa
  become: yes
  roles:
    - graphite/centos
    - graphite/apache
    - graphite/graphite
  environment:
    http_proxy: http://proxy.sla.getthere.net:80
    https_proxy: http://proxy.sla.getthere.net:80
